name = "regtest"

# Development environment (folders added to the path when project is loaded)
[folders]
path = [
    ".",
]
test = [
    "tests",
]

[dependencies]

[project]
summary = "Tool to add regression checkpoints to messy MATLAB code"

[[package]]
configuration-name = "Release"

name = "regtest"
display-name = "MATLAB Regression Test"
version = "0.3.2"

# Should match UUID assigned by File Exchange
id = "dbc96ef9-8f41-45ce-a66c-c07f99ab56b4"

# Execution environment (folders added to end-user path)
package-root = "/"
folders.path = ["."]

use-license-bsd = true
provider.name = "Martin Herrerias Azcue"
provider.email = "martin.herreriasazcue@manchester.ac.uk"
provider.organization = "University of Manchester"
summary = "Tool to add regression checkpoints to messy MATLAB code"
description = "A development tool for refactoring MATLAB code with little or no tests. Insert minimally invasive checkpoints to capture workspace snapshots, then use them to verify that refactored code produces the same results."

getting-started-file = "example/getting_started.m"
preview-image-file = "resources/spaghetti.png"

release-compatibility = "22.1.* - 26.2.*"
supported-platforms = [
    "windows",
    "linux",
    "macos",
]
